-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.series
(
    href text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT series_pkey PRIMARY KEY (href)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.series
    OWNER to postgres;

GRANT ALL ON TABLE public.series TO anon;

GRANT ALL ON TABLE public.series TO authenticated;

GRANT ALL ON TABLE public.series TO postgres;

GRANT ALL ON TABLE public.series TO service_role;
CREATE UNIQUE INDEX IF NOT EXISTS series_href_key
    ON public.series USING btree
    (href COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.users
(
    href text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (href)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

GRANT ALL ON TABLE public.users TO anon;

GRANT ALL ON TABLE public.users TO authenticated;

GRANT ALL ON TABLE public.users TO postgres;

GRANT ALL ON TABLE public.users TO service_role;
CREATE UNIQUE INDEX IF NOT EXISTS users_href_key
    ON public.users USING btree
    (href COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE TABLE IF NOT EXISTS public.articles
(
    href text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    content text COLLATE pg_catalog."default" NOT NULL,
    tags text COLLATE pg_catalog."default",
    genre text COLLATE pg_catalog."default",
    publish_at text COLLATE pg_catalog."default" NOT NULL,
    author_href text COLLATE pg_catalog."default",
    series_href text COLLATE pg_catalog."default" NOT NULL,
    series_no text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT articles_pkey PRIMARY KEY (href),
    CONSTRAINT articles_author_href_fkey FOREIGN KEY (author_href)
        REFERENCES public.users (href) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    CONSTRAINT articles_series_href_fkey FOREIGN KEY (series_href)
        REFERENCES public.series (href) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE RESTRICT
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.articles
    OWNER to postgres;

GRANT ALL ON TABLE public.articles TO anon;

GRANT ALL ON TABLE public.articles TO authenticated;

GRANT ALL ON TABLE public.articles TO postgres;

GRANT ALL ON TABLE public.articles TO service_role;
CREATE UNIQUE INDEX IF NOT EXISTS articles_href_key
    ON public.articles USING btree
    (href COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS articles_title_idx
    ON public.articles USING btree
    (title COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
