app = "over-engineering-backend"

[build]
  image = "tainvecs/over_engineering-backend:v0.0.1"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 5000

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"