app = "over-engineering-backend-staging"

[build]
  image = "tainvecs/over_engineering-backend:v0.0.20"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

# [[services]]
#   internal_port = 7700
#   protocol = "tcp"

#   [services.concurrency]
#     hard_limit = 25
#     soft_limit = 20
#     type = "connections"

#   [[services.ports]]
#     handlers = ["http"]
#     port = 7700
#     force_https = true

#   [[services.ports]]
#     handlers = ["tls", "http"]
#     port = 7700

#   [[services.tcp_checks]]
#     grace_period = "1s"
#     interval = "15s"
#     restart_limit = 0
#     timeout = "2s"


[mounts]
  source="ms_data_staging"
  destination="/search_engine/data"