name: Scrape Schedule

on:
  schedule:
    - cron: '0 0 * * 0'

  workflow_dispatch: {}

jobs:
  execute_staging:
    uses: ./.github/workflows/scrape-articles.yml
    with:
      environment: staging

  execute_production:
    uses: ./.github/workflows/scrape-articles.yml
    with:
      environment: production
